In [9]:
from tkinter import dialog

import pandas as pd

df = pd.read_json("script-bag-of-words.json")

print(df.tail())

   episodeAlt  seasonNum  episodeNum                    episodeTitle  \
68       S8E2          8           2  A Knight of the Seven Kingdoms
69       S8E3          8           3                  The Long Night
70       S8E4          8           4          The Last of the Starks
71       S8E5          8           5                       The Bells
72       S8E6          8           6                 The Iron Throne

                                                 text
68  [{'name': 'Daenerys Targaryen', 'text': 'About...
69  [{'name': 'Northman #1', 'text': 'Oi!'}, {'nam...
70  [{'name': 'Jon Snow', 'text': 'And Everyone It...
71  [{'name': 'Lord Varys', 'text': 'And? Come Not...
72  [{'name': 'Tyrion Lannister', 'text': 'I'll fi...

In [11]:
dialouge={}
for index,row in df.iterrows():
    for item in row['text']:
        if item['name'] in dialouge:
            dialouge[item['name']] = dialouge[item['name']]+item['text']
        else:
            dialouge[item['name']] = item['text'] + " "

In [13]:
len(dialouge)

817

In [18]:
new_df=pd.DataFrame()
new_df['character'] = dialouge.keys()
new_df['words'] = dialouge.values()
new_df['num_words'] = new_df['words'].apply(lambda x: len(x.split()))
new_df = new_df.sort_values('num_words',ascending=False)
new_df = new_df.head(100)
new_df.head()

,character,words,num_words
17,Tyrion Lannister,It Mmh. Northern about girls. is say the they ...,25924
13,Cersei Lannister,And And Casterly One Rock. When about afraid. ...,14294
3,Jon Snow,Father's Go on. watching. And mother. yourBran...,11488
20,Daenerys Targaryen,We've a and anything. asked been for for guest...,11202
12,Jaime Lannister,"As I It's brother, duty feel it's much. my sho...",10823

In [20]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(stop_words='english')
embeddings = cv.fit_transform(new_df['words']).toarray()
embeddings.shape
embeddings = embeddings.astype('float64')

In [23]:
from sklearn.manifold import TSNE
tsne = TSNE(n_components=2, verbose=1, random_state=123)
z = tsne.fit_transform(embeddings)
new_df['x'] = z.T[0]
new_df['y'] = z.T[1]
new_df.head()

[t-SNE] Computing 91 nearest neighbors...
[t-SNE] Indexed 100 samples in 0.006s...
[t-SNE] Computed neighbors for 100 samples in 0.021s...
[t-SNE] Computed conditional probabilities for sample 100 / 100
[t-SNE] Mean sigma: 14.377887
[t-SNE] KL divergence after 250 iterations with early exaggeration: 63.933544
[t-SNE] KL divergence after 850 iterations: 0.292373

,character,words,num_words,x,y
17,Tyrion Lannister,It Mmh. Northern about girls. is say the they ...,25924,-0.669299,-3.554492
13,Cersei Lannister,And And Casterly One Rock. When about afraid. ...,14294,-0.653763,-3.306497
3,Jon Snow,Father's Go on. watching. And mother. yourBran...,11488,-0.892448,-3.193901
20,Daenerys Targaryen,We've a and anything. asked been for for guest...,11202,-0.260003,-2.804462
12,Jaime Lannister,"As I It's brother, duty feel it's much. my sho...",10823,-0.748884,-3.125681

In [25]:
!pip install plotly
import plotly.express as px
fig = px.scatter(new_df.head(25), x="x", y="y", color="character")
fig.show()

[notice] A new release of pip is available: 26.0.1 -> 26.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

Collecting plotly
  Downloading plotly-6.8.0-py3-none-any.whl.metadata (9.0 kB)
Requirement already satisfied: narwhals>=1.15.1 in .\.venv\Lib\site-packages (from plotly) (2.21.2)
Requirement already satisfied: packaging in .\.venv\Lib\site-packages (from plotly) (26.2)
Downloading plotly-6.8.0-py3-none-any.whl (9.9 MB)
   ---------------------------------------- 0.0/9.9 MB ? eta -:--:--
   --- ------------------------------------ 0.8/9.9 MB 6.4 MB/s eta 0:00:02
   ---- ----------------------------------- 1.0/9.9 MB 8.1 MB/s eta 0:00:02
   -------- ------------------------------- 2.1/9.9 MB 3.7 MB/s eta 0:00:03
   -------- ------------------------------- 2.1/9.9 MB 3.7 MB/s eta 0:00:03
   -------- ------------------------------- 2.1/9.9 MB 3.7 MB/s eta 0:00:03
   -------- ------------------------------- 2.1/9.9 MB 3.7 MB/s eta 0:00:03
   -------- ------------------------------- 2.1/9.9 MB 3.7 MB/s eta 0:00:03
   -------- ------------------------------- 2.1/9.9 MB 3.7 MB/s eta 0:00:03
   ---------- ----------------------------- 2.6/9.9 MB 1.4 MB/s eta 0:00:06
   -------------- ------------------------- 3.7/9.9 MB 1.7 MB/s eta 0:00:04
   ---------------- ----------------------- 4.2/9.9 MB 1.9 MB/s eta 0:00:03
   ------------------- -------------------- 4.7/9.9 MB 1.8 MB/s eta 0:00:03
   --------------------- ------------------ 5.2/9.9 MB 2.0 MB/s eta 0:00:03
   --------------------- ------------------ 5.2/9.9 MB 2.0 MB/s eta 0:00:03
   ---------------------- ----------------- 5.5/9.9 MB 1.7 MB/s eta 0:00:03
   ------------------------- -------------- 6.3/9.9 MB 1.9 MB/s eta 0:00:02
   ------------------------- -------------- 6.3/9.9 MB 1.9 MB/s eta 0:00:02
   ------------------------- -------------- 6.3/9.9 MB 1.9 MB/s eta 0:00:02
   ---------------------------- ----------- 7.1/9.9 MB 1.8 MB/s eta 0:00:02
   ----------------------------- ---------- 7.3/9.9 MB 1.8 MB/s eta 0:00:02
   ----------------------------- ---------- 7.3/9.9 MB 1.8 MB/s eta 0:00:02
   ----------------------------- ---------- 7.3/9.9 MB 1.8 MB/s eta 0:00:02
   ----------------------------- ---------- 7.3/9.9 MB 1.8 MB/s eta 0:00:02
   ------------------------------- -------- 7.9/9.9 MB 1.5 MB/s eta 0:00:02
   --------------------------------- ------ 8.4/9.9 MB 1.6 MB/s eta 0:00:01
   ------------------------------------- -- 9.2/9.9 MB 1.7 MB/s eta 0:00:01
   -------------------------------------- - 9.4/9.9 MB 1.7 MB/s eta 0:00:01
   ---------------------------------------- 9.9/9.9 MB 1.7 MB/s  0:00:05
Installing collected packages: plotly
Successfully installed plotly-6.8.0